---
- name:  Deploy WebApp
  hosts: all
  sudo:  yes

  roles:
    - { role: webapp,  sudo_user: $user }
    - { role: unicorn, sudo_user: $user }
    - nginx
    - { role: bluepill, sudo_user: $user }
    - { role: capistrano, sudo_user: $user }
