---
- name: Install Bluepill
  gem: name=bluepill
  sudo_user: $user

- name: Generate Bluepill config
  template: src=blue_pill.j2 dest=/home/$user/$appname/www/config/ owner=$user group=$user mode=664

