---
- name: Install Bluepill
  gem: name=bluepill

- name: Generate Bluepill config
  template: src=blue_pill.j2 dest=/home/$user/$app_name/www/config/blue.pill

- name: Generate Bluepill init file
  template: src=bluepill_init.j2 dest=/etc/init.d/bluepill-{{ app_name }} mode=0755 owner=root group=root
  sudo_user: root
