---
- name: Add user
  user: name=$user shell='/bin/bash'

- name: Install deb pkg
  apt: pkg=$item state=latest update_cache=yes
  with_items:
    - build-essential
    - libssl-dev
    - libreadline-gplv2-dev
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - tklib
    - zlib1g-dev
    - curl
    - git
