---
- name: Install Capistrano gem
  gem: name=capistrano
  sudo_user: $user

#- name: Capistrano init?

- name: Generate Capistrano config
  template: src=deploy_rb.j2 dest=/home/$user/$app_name/www/config/deploy.rb owner=$user group=$user mode=664
