--- 
- name: check rbenv
  action: shell test -d $home/.rbenv && echo "yes"
  register: rbenv_installed

- include: rbenv.yml
  when: rbenv_installed.stdout != "yes"

- name: check ruby version
  action: shell test -d $home/.rbenv/versions/$ruby_version && echo "yes"
  register: installed_ruby_version

- include: ruby.yml
  when: installed_ruby_version.stdout != "yes"