---
- name: install Ruby
  shell: "{{ home }}/.rbenv/bin/rbenv install {{ ruby_version }}"
  notify: initialize rbenv

- name: make ruby global
  shell: "{{ home }}/.rbenv/bin/rbenv global {{ ruby_version }}"